import { existsSync } from "node:fs";
import { join, resolve } from "node:path";

import pkg from "../../package.json" with { type: "json" };

export const BOOTSTRAP_HARNESSES = ["claude", "codex", "opencode", "hermes"] as const;
export type BootstrapHarness = typeof BOOTSTRAP_HARNESSES[number];

interface Artifact {
  path: string;
  content: string;
  install: string;
}

function claudeHooks(): string {
  const command = (state: string) => `pharos tmux dispatch ${state} --tool=claude`;
  const render = "pharos tmux render --tool=claude";
  return `${JSON.stringify({
    hooks: {
      PreToolUse: [{ matcher: ".*", hooks: [{ type: "command", command: command("tool") }] }],
      PostToolUse: [{ matcher: ".*", hooks: [{ type: "command", command: command("think") }, { type: "command", command: render }] }],
      UserPromptSubmit: [{ hooks: [{ type: "command", command: command("think") }, { type: "command", command: render }] }],
      Stop: [{ hooks: [{ type: "command", command: render }, { type: "command", command: command("off") }] }],
      Notification: [{ hooks: [{ type: "command", command: "pharos tmux dispatch notify --tool=claude" }, { type: "command", command: render }] }],
      SessionStart: [{ hooks: [{ type: "command", command: command("off") }, { type: "command", command: render }] }],
      SessionEnd: [{ hooks: [{ type: "command", command: render }, { type: "command", command: command("off") }] }],
    },
  }, null, 2)}\n`;
}

function codexHooks(): string {
  const command = (state: string) => `pharos tmux dispatch ${state} --tool=codex`;
  const render = "pharos tmux render --tool=codex";
  return `${JSON.stringify({
    description: "Render Codex activity and session metrics through Pharos in tmux.",
    hooks: {
      SessionStart: [{ hooks: [{ type: "command", command: command("off") }, { type: "command", command: render }] }],
      PreToolUse: [{ matcher: "*", hooks: [{ type: "command", command: command("tool") }] }],
      PostToolUse: [{ matcher: "*", hooks: [{ type: "command", command: command("think") }, { type: "command", command: render }] }],
      PermissionRequest: [{ matcher: "*", hooks: [{ type: "command", command: command("ask") }, { type: "command", command: render }] }],
      UserPromptSubmit: [{ hooks: [{ type: "command", command: command("think") }, { type: "command", command: render }] }],
      Stop: [{ hooks: [{ type: "command", command: render }, { type: "command", command: command("off") }] }],
      SessionEnd: [{ hooks: [{ type: "command", command: render, timeout: 3 }, { type: "command", command: command("off"), timeout: 3 }] }],
    },
  }, null, 2)}\n`;
}

function opencodeBridge(): string {
  return `// Generated by Pharos. Copy to ~/.config/opencode/plugins/pharos-bridge.ts.\nconst renderEvery = 5000;\nlet lastState; let lastRender = 0;\nexport const PharosBridge = async ({ $ }) => ({ event: async ({ event }) => {\n  const p = event.properties ?? {}; const part = p.part; let state;\n  if (event.type === "session.idle") state = "off";\n  else if (event.type === "message.part.updated" && part?.type === "tool" && part.state?.status === "running") state = part.tool === "question" ? "ask" : "tool";\n  else if (event.type === "message.part.updated" && ["text", "reasoning", "step-start"].includes(part?.type)) state = "think";\n  try { if (state && state !== lastState) { lastState = state; await $\`pharos tmux dispatch \${state} --tool=opencode\`; } } catch {}\n  const sessionId = p.sessionID; const now = Date.now();\n  if (sessionId && (event.type === "session.idle" || (event.type === "session.updated" && now - lastRender >= renderEvery))) {\n    lastRender = now; try { const payload = JSON.stringify({ session_id: sessionId }); await $\`echo \${payload} | pharos tmux render --tool=opencode\`; } catch {}\n  }\n}});\n`;
}

function hermesHook(): string {
  return `#!/bin/sh\n# Generated by Pharos. Hermes sends its shell-hook JSON on stdin.\nset -eu\npayload=$(cat)\nevent=$(printf '%s' "$payload" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')\ncase "$event" in\n  pre_tool_call) pharos tmux dispatch tool --tool=hermes ;;\n  post_tool_call) pharos tmux dispatch think --tool=hermes ;;\n  pre_llm_call) pharos tmux dispatch think --tool=hermes ;;\n  on_session_start) pharos tmux dispatch off --tool=hermes ;;\n  on_session_end) pharos tmux dispatch off --tool=hermes ;;\nesac\ncase "$event" in\n  post_tool_call|on_session_start|on_session_end) printf '%s' "$payload" | pharos tmux render --tool=hermes ;;\nesac\n`;
}

function hermesConfig(): string {
  return `# Merge these entries into ~/.hermes/config.yaml.\nhooks:\n  on_session_start:\n    - command: ~/.hermes/agent-hooks/pharos\n  pre_llm_call:\n    - command: ~/.hermes/agent-hooks/pharos\n  pre_tool_call:\n    - command: ~/.hermes/agent-hooks/pharos\n  post_tool_call:\n    - command: ~/.hermes/agent-hooks/pharos\n  on_session_end:\n    - command: ~/.hermes/agent-hooks/pharos\n`;
}

function artifactsFor(harness: BootstrapHarness): Artifact[] {
  switch (harness) {
    case "claude": return [{ path: "claude/settings.pharos.json", content: claudeHooks(), install: "Merge its hooks object into ~/.claude/settings.json." }];
    case "codex": return [{ path: "codex/hooks.json", content: codexHooks(), install: "Install as ~/.codex/hooks.json, then review it with Codex /hooks." }];
    case "opencode": return [{ path: "opencode/pharos-bridge.ts", content: opencodeBridge(), install: "Install as ~/.config/opencode/plugins/pharos-bridge.ts and restart OpenCode." }];
    case "hermes": return [
      { path: "hermes/pharos", content: hermesHook(), install: "Install as ~/.hermes/agent-hooks/pharos and make it executable." },
      { path: "hermes/hooks.pharos.yaml", content: hermesConfig(), install: "Merge into ~/.hermes/config.yaml, then approve/check with `hermes hooks doctor`." },
    ];
  }
}

function parseArgs(args: string[]): { harnesses: BootstrapHarness[]; output: string; force: boolean } | null {
  let harness = "";
  let output = "";
  let force = false;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]!;
    if (arg === "--force") force = true;
    else if (arg === "--harness") harness = args[++i] ?? "";
    else if (arg.startsWith("--harness=")) harness = arg.slice("--harness=".length);
    else if (arg === "--output") output = args[++i] ?? "";
    else if (arg.startsWith("--output=")) output = arg.slice("--output=".length);
    else return null;
  }
  const harnesses = harness === "all" ? [...BOOTSTRAP_HARNESSES] : BOOTSTRAP_HARNESSES.includes(harness as BootstrapHarness) ? [harness as BootstrapHarness] : [];
  return harnesses.length && output ? { harnesses, output: resolve(output), force } : null;
}

/** Emits ready-to-copy harness integration artifacts without ever touching a
 * harness-owned config file. This makes it safe for Nix/home-manager users
 * and gives every generated script an auditable source.
 *
 * Returns the process exit code rather than setting `process.exitCode`
 * itself: this runs in-process inside tests too, and a global process
 * mutation there would outlive the test that triggered it. Only the real
 * CLI entrypoint (src/index.ts) touches `process.exitCode`. */
export async function generateBootstrapBundle(args: string[]): Promise<number> {
  const parsed = parseArgs(args);
  if (!parsed) {
    console.error("Usage: pharos init --harness <claude|codex|opencode|hermes|all> --output <directory> [--force]");
    return 2;
  }
  if (existsSync(parsed.output) && !parsed.force) {
    console.error(`pharos: ${parsed.output} already exists; use --force to write generated artifacts there.`);
    return 1;
  }
  const artifacts = parsed.harnesses.flatMap(artifactsFor);
  for (const artifact of artifacts) {
    const path = join(parsed.output, artifact.path);
    await Bun.write(path, artifact.content);
    if (artifact.path === "hermes/pharos") await Bun.spawn(["chmod", "+x", path]).exited;
  }
  await Bun.write(join(parsed.output, "manifest.json"), `${JSON.stringify({
    pharosVersion: pkg.version,
    harnesses: parsed.harnesses,
    artifacts: artifacts.map(({ path, install }) => ({ path, install })),
    next: "Run `pharos tmux init` from a tmux pane after installing the desired artifact.",
  }, null, 2)}\n`);
  console.log(`pharos: wrote ${artifacts.length} artifact(s) to ${parsed.output}`);
  return 0;
}
